name: "Z - Labs: News from the lab"
baseurl: ""
description: ""
url: "https://mzet-.github.io/"
github_username: mzet-

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

kramdown:
smart_quotes: ["apos", "apos", "quot", "quot"]
